name=OLLO
version=1.0.0
author=ROBOTIS
maintainer=Will Son <willson@robotis.com>
sentence=Examples for OLLO Sensors
paragraph=
category=Other
url=https://https://emanual.robotis.com/docs/en/parts/sensor/
architectures=samd
